---
- name: Include vars file
  ansible.builtin.include_vars: nginx.yaml
  
- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Copy nginx configuration
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf
#  notify: restart nginx

- name: Copy nginx ssl configuration
  template: src=ssl.j2 dest=/etc/nginx/conf.d/ssl.conf
#  notify: restart nginx

- name: copy ssl directory
  copy:
    src: ssl
    dest: /etc/
    directory_mode:
  tags:
    - parentdir

- name: Create folder for synchronize
  command: mkdir /var/www
  become: true
  become_user: root

- name: Create folder for synchronize
  command: mkdir /var/www/html
  become: true
  become_user: root

- name: nginx service state
  service:
    name: nginx
    state: started
    enabled: yes

...
