---
- name: Include vars file
  ansible.builtin.include_vars: httpd.yaml
  
- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: download remi repo rpm
  get_url: url=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm dest=/root/  

- name: install remi repo rpm
  yum: name=/root/remi-release-7.rpm state=present

- name: Install http, php and php-fpm
  yum:
    enablerepo: "remi,remi-php72"
    name: "{{ item }}"
    state: latest
  loop:
    - httpd
    - php-mcrypt
    - php-cli
    - php-gd
    - php-curl
    - php-ldap
    - php-zip
    - php-fileinfo
    - php
    - php72
    - php-fpm
    - php-mbstring
    - php-IDNA_Convert
    - php-PHPMailer
    - php-process
    - php-simplepie
    - php-xml
    - php-mysql

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Copy global httpd configuration
  template: src=httpd.j2 dest=/etc/httpd/httpd.conf
#  notify: restart nginx

- name: Copy backend httpd configuration
  template: src=wordpress.j2 dest=/etc/httpd/conf.d/wordpress.conf
#  notify: restart nginx

- name: chown user "apache"
  shell: "chown -R apache.apache /var/www/html/"

- name: Set permissions for directories
  shell: "/usr/bin/find /var/www/html/ -type d -exec chmod 750 {} \\;"

- name: Set permissions for files
  shell: "/usr/bin/find /var/www/html/ -type f -exec chmod 640 {} \\;"

- name: httpd service state
  service:
    name: httpd
    state: started
    enabled: yes

- name: Disable default pool
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm
  when: (ansible_hostname == "backend1")

- name: Copy php-fpm configuration
  template: src=www.j2 dest=/etc/php-fpm.d/www.conf
  notify: restart php-fpm
  when: (ansible_hostname == "backend1")
...
